### ISSUE TITLE
تاریخ جاری

### ISSUE THREAD

**Issue by farzinborujerdi** [omidgolparvar/IDPersianDatePicker#1]
سلام
اول از همه کلی خسته نباشید بابت این تقویم زیبا و کاربردی
دستتون درد نکنه حسابی

یک نکته ای که این تقویم داره اینه که مثلا در مورد تاریخ تولد وقتی مینیمم تاریخ قابل انتخاب رو میبریم ۴۰-۵۰ سال قبل کلا تقویم هم از همون تاریخ باز میشه و نمیشه برای روز پیش فرض رو انتخاب کرد که مثلا یک یا چند روز قبل از ماکزیمم تاریخ قابل انتخاب دیفالتش باشه ...

یک مورد دیگه هم اینکه نمیشه یهویی یک تاریخ رو به سرعت عوض کرد ... باید ماه به ماه و سال به سال بریم تا برسیم به تاریخ مورد نظر ...

ایده ای برای این دو مورد هست ؟

**Comment by omidgolparvar** [comment]
<div dir='rtl'>
سلام دوست عزیز. 

خوشحالم که چیزی که پیاده‌سازی کردم، براتون مفید بوده. 😊

در مورد نکاتی که اشاره کردین:

- وقتی انتخاب‌کننده نمایش داده میشه، الان بصورت پیشفرض ماه‌ای نمایش داده میشه که کمینه تاریخ قابل انتخاب داخل‌اش هست. برای همین وقتی مثلا کمینه رو تاریخی توی چند سال پیش تنظیم می‌کنیم، همون ماه مورد نظر توی چند سال پیش نمایش داده میشه. واقعیت‌اش اون موقعی که پیاده‌سازی می‌کردم، فکر این مساله رو نکرده بودم که ممکنه فاصله بین تاریخ‌های کمینه و بیشینه قابل انتخاب چند ۱۰ سال باشه! 😅
  - برای بهبود این رویه، میشه یه مشخصه اضافه کرد، که مشخص‌کننده **تاریخ پیش‌فرض نمایش** باشه؛ و وقتی انتخاب‌کننده نمایش داده شد، اون نمایش تاریخ داده بشه.
    - پیاده‌سازی این روند فکر نمی‌کنم مشکل خاصی داشته باشه.
    - البته در کنار این مشخصه، یه مشخصه دیگه هم می‌خوام اضافه کنم برای «تاریخ‌های انتخاب‌شده پیشفرض» و موقع نمایش، این تاریخ‌ها اولویت بیشتری نسبت به تاریخ پیش‌فرض نمایش دارن.

- در مورد اینکه نمیشه تقویم رو سریع ورق زد و برای جابجایی باید ماه به ماه جلو یا عقب بریم، دوتا رویه میشه پیاده‌سازی کرد:

  - دوتا دکمه در کنار دکمه‌های «ماه قبل» و «ماه بعد» بذاریم که برای رفتن به «سال قبل» و «سال بعد» استفاده بشه.
    - پیاده‌سازی این رویه ساده‌ست و با اضافه‌کردن دوتا دکمه کار حل میشه.
  - میشه بطوری پیاده‌سازی کرد که مثلا وقتی روی عبارت وسط که ماه و سال رو مشخص می‌کنه تپ شد، ویویی نمایش داده بشه برای انتخاب سریع ماه و سال.
    - پیاده‌سازی به آسونی قبلی نیست، و باید زمان صرف کرد تا یه رویه بهینه (و البته خوشگل 😁) براش پیدا کرد.

من رویه‌ها رو بررسی می‌کنم و سعی می‌کنم برای نسخه بعدی، هر دوتا رویه پیاده‌سازی شده باشه؛ بطوریکه با توجه به بازه قابل انتخاب، خودش تشخیص بده که برای جابجایی از کدوم روند استفاده بشه.

بهرحال تنکیوو. 😉
</div>

**Comment by farzinborujerdi** [comment]
> سلام دوست عزیز.
> خوشحالم که چیزی که پیاده‌سازی کردم، براتون مفید بوده. 😊
> 
> در مورد نکاتی که اشاره کردین:
> 
> * وقتی انتخاب‌کننده نمایش داده میشه، الان بصورت پیشفرض ماه‌ای نمایش داده میشه که کمینه تاریخ قابل انتخاب داخل‌اش هست. برای همین وقتی مثلا کمینه رو تاریخی توی چند سال پیش تنظیم می‌کنیم، همون ماه مورد نظر توی چند سال پیش نمایش داده میشه. واقعیت‌اش اون موقعی که پیاده‌سازی می‌کردم، فکر این مساله رو نکرده بودم که ممکنه فاصله بین تاریخ‌های کمینه و بیشینه قابل انتخاب چند ۱۰ سال باشه! 😅
>   
>   * برای بهبود این رویه، میشه یه مشخصه اضافه کرد، که مشخص‌کننده **تاریخ پیش‌فرض نمایش** باشه؛ و وقتی انتخاب‌کننده نمایش داده شد، اون نمایش تاریخ داده بشه.
>     
>     * پیاده‌سازی این روند فکر نمی‌کنم مشکل خاصی داشته باشه.
>     * البته در کنار این مشخصه، یه مشخصه دیگه هم می‌خوام اضافه کنم برای «تاریخ‌های انتخاب‌شده پیشفرض» و موقع نمایش، این تاریخ‌ها اولویت بیشتری نسبت به تاریخ پیش‌فرض نمایش دارن.
> * در مورد اینکه نمیشه تقویم رو سریع ورق زد و برای جابجایی باید ماه به ماه جلو یا عقب بریم، دوتا رویه میشه پیاده‌سازی کرد:
>   
>   * دوتا دکمه در کنار دکمه‌های «ماه قبل» و «ماه بعد» بذاریم که برای رفتن به «سال قبل» و «سال بعد» استفاده بشه.
>     
>     * پیاده‌سازی این رویه ساده‌ست و با اضافه‌کردن دوتا دکمه کار حل میشه.
>   * میشه بطوری پیاده‌سازی کرد که مثلا وقتی روی عبارت وسط که ماه و سال رو مشخص می‌کنه تپ شد، ویویی نمایش داده بشه برای انتخاب سریع ماه و سال.
>     
>     * پیاده‌سازی به آسونی قبلی نیست، و باید زمان صرف کرد تا یه رویه بهینه (و البته خوشگل 😁) براش پیدا کرد.
> 
> من رویه‌ها رو بررسی می‌کنم و سعی می‌کنم برای نسخه بعدی، هر دوتا رویه پیاده‌سازی شده باشه؛ بطوریکه با توجه به بازه قابل انتخاب، خودش تشخیص بده که برای جابجایی از کدوم روند استفاده بشه.
> 
> بهرحال تنکیوو. 😉

آقا اولا مجدد دمت گرم ...
دوما هر دوتاش کار خودته ، دیگه بزنیم توی پاد فایل و بریم دعا کنیم به جون شما :-)
و اینکه هر دوتاش از جمله نیاز های اساسی هر دیت پیکری هستن خصوصا اگه کاربردش تاریخ نولد باشه که بدون شک شما هم دیدین ولی وقت نشده حتما

خلاصه که بشدت دست به دامنتونیم :-)

**Comment by omidgolparvar** [comment]
<div dir='rtl'>

نسخه جدیدی منتشر شد. 
بگیرین و پروژه Example رو یه نگاهی بندازین.

- رویه استفاده تا حد زیادی تغییر کرده. البته کلیات شبیه هستن.
- دوتا دکمه برای «سال قبل» و «سال بعد» اضافه شدن.
- عنوان «ماه / سال» که بین دکمه‌ها قرار داشت، خودش دکمه‌ای برای جابه‌جایی سریع بین صفحات تقویم شده. البته این دکمه زمانی فعال هست که فاصله بین کمینه و بیشینه تاریخ‌های تنظیماتی، بیشتر از ۲ سال باشه. نمونه رابط کاربری پیاده‌سازی‌شده، توی صفحه اصلی یا همون ReadMe هست.
- گزینه‌های «تاریخ‌های از پیش انتخاب‌شده» و «تاریخ نمایشی پیش‌فرض» و غیره اضافه شدن؛ و توضیحات‌شون توی ReadMe هست.

در کل یه نگاهی به نسخه ۲ بندازین و اگه مورد دیگه بود بگین.  😉

یه مورد دیگه اینکه اگه دوست داشتین، بگین از این کتابخونه توی چه اپی دارین استفاده می‌کنین، تا توی صفحه ReadMe بیانش کنم.

ممنون.
😊
</div>

**Comment by farzinborujerdi** [comment]
آقا اول از همه دمت خیلی گرم
برنامه رو بذاریم روی استور حتما نامش رو تقدیم میکنم خدمتتون

ولی الان موضوع اینه که کتابخونه خطا داره موقع پرزنت شدن

**Comment by omidgolparvar** [comment]
<div dir='rtl'>

من همین الان نسخه منتشرشده توی Cocoapod رو توی یه پروژه تستی نصب کردم، و مشکلی برای نمایش ندیدم.


کدی که برای نمایش استفاده می‌کنین رو بهمراه خطایی که دریافت می‌کنین ارائه بدین، تا بتونم بررسی کنم.

</div>

**Comment by farzin680** [comment]
> من همین الان نسخه منتشرشده توی Cocoapod رو توی یه پروژه تستی نصب کردم، و مشکلی برای نمایش ندیدم.
> 
> کدی که برای نمایش استفاده می‌کنین رو بهمراه خطایی که دریافت می‌کنین ارائه بدین، تا بتونم بررسی کنم.

راست میگی درسته :-) 👍

**Comment by farzinborujerdi** [comment]
> من همین الان نسخه منتشرشده توی Cocoapod رو توی یه پروژه تستی نصب کردم، و مشکلی برای نمایش ندیدم.
> 
> کدی که برای نمایش استفاده می‌کنین رو بهمراه خطایی که دریافت می‌کنین ارائه بدین، تا بتونم بررسی کنم.

راست میگی درست کار میکنه :-) 👍
