### ISSUE TITLE
انتخاب جمعه ها غیر فعال است

### ISSUE THREAD

**Issue by sadeghgoo** [omidgolparvar/IDPersianDatePicker#4]
من Sample همین ریپوزیتوری رو کلون کردم و ران کردم اما جمعه ها غیر فعال است

iOS: 14.5 

![Screen Shot 2021-12-23 at 9 23 28 AM](https://user-images.githubusercontent.com/43542836/147194978-438c0192-8a1e-44ea-97aa-38ea2ca67fd2.png)

**Comment by omidgolparvar** [comment]
@sadeghgoo 
صادق جان سلام. 
توی پروژه تستی، بصورت تستی، جمعه‌ها رو غیرفعال در نظر گرفتم. قابل تغییر هست. اگه مورد دیگه‌ای بود، حتما بگو. 

تنکیووو.

**Comment by sadeghgoo** [comment]
سلام :)
آره بعد اینکه delegate رو دیدم متوجه شدم و issue رو close کردم. 

مرسی از پیگیریت
